INSERT INTO agent (ime, prezime, jmbg, adresa, telefon, korisnicko_ime, sifra, email) VALUES ('Milos', 'Ratkovic', '0404993782851', 'Vojvode Stepe 321', '+381653731577', 'Milos', 'samsung4', 'dowsha032@gmail.com');
INSERT INTO tip_nekretnine (tip) VALUES ('Kuca');
INSERT INTO tip_nekretnine (tip) VALUES ('Stan');
INSERT INTO tip_nekretnine (tip) VALUES ('Lokal');
INSERT INTO tip_nekretnine (tip) VALUES ('Garaza');
INSERT INTO opstina (naziv) VALUES ('Barajevo');
INSERT INTO opstina (naziv) VALUES ('Vozdovac');
INSERT INTO opstina (naziv) VALUES ('Vracar');
INSERT INTO opstina (naziv) VALUES ('Grocka');
INSERT INTO opstina (naziv) VALUES ('Zvezdara');
INSERT INTO opstina (naziv) VALUES ('Zemun');
INSERT INTO opstina (naziv) VALUES ('Lazarevac');
INSERT INTO opstina (naziv) VALUES ('Mladenovac');
INSERT INTO opstina (naziv) VALUES ('Novi Beograd');
INSERT INTO opstina (naziv) VALUES ('Obrenovac');
INSERT INTO opstina (naziv) VALUES ('Rakovica');
INSERT INTO opstina (naziv) VALUES ('Savski Venac');
INSERT INTO opstina (naziv) VALUES ('Sopot');
INSERT INTO opstina (naziv) VALUES ('Stari Grad');
INSERT INTO opstina (naziv) VALUES ('Surcin');
INSERT INTO opstina (naziv) VALUES ('Cukarica');
INSERT INTO `agent` (`id`, `ime`, `prezime`, `jmbg`, `adresa`, `telefon`, `korisnicko_ime`, `sifra`, `email`) VALUES (NULL, 'Zika', 'Zikic', '2509991710123', 'Mite Balije 32', '011 2346754', 'zika', 'zika', 'zilecar@starmail.com');
INSERT INTO `agent` (`id`, `ime`, `prezime`, `jmbg`, `adresa`, `telefon`, `korisnicko_ime`, `sifra`, `email`) VALUES (NULL, 'Mika', 'Mikic', '2108987710453', 'Laze Simica 12/2', '011 5432341', 'mika', 'mika', 'mika@gmail.com');
INSERT INTO `kupac` (`id`, `ime`, `prezime`, `jmbg`, `adresa`, `telefon`, `korisnicko_ime`, `sifra`, `email`) VALUES (NULL, 'Pera', 'Peric', '1111971710101', 'Bacansofisanova 45b', '011 2453345', 'pera', 'pera', 'peramanijak@mail.ru');
INSERT INTO `kupac` (`id`, `ime`, `prezime`, `jmbg`, `adresa`, `telefon`, `korisnicko_ime`, `sifra`, `email`) VALUES (NULL, 'Miroslava', 'Miroslavovic', '1012965710020', 'Mire Berkovica 78', '031 2313332', 'mirka', 'mirka', 'mirkakuvarica@gmail.com');